openapi: 3.0.3
info:
  title: ETLB Aircraft Document Service - OpenAPI 3.0
  description: |-
  termsOfService: https://swagger.io/terms/
  contact:
    email: etlb@aviatar.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
tags:
  - name: image-search
    description: Image search
servers:
  - url: http://localhost:8080/api/v1
paths:
  /search:
    get:
      tags:
        - image-search
      summary: >
        Search for Images
      description: >
        Search for Images
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
          description: the search term
      responses:
        '200':
          description: returns list of items and an empty arry in case the query has no results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDataItem'
components:
  schemas:
    UserLink:
      type: object
      properties:
        id:
          type: string
        href:
          type: string

    UserDataItem:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        title:
          type: string
        keywords:
          type: array
          items:
            type: string
          default: [ ]
        nasaId:
          type: string
        dateCreated:
          type: string
          format: date-time
          example: '2019-07-15T19:08:21.42Z'
        links:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/UserLink'





