logging:
  level:
    org.hibernate.SQL: OFF
    'org.springframework.web': DEBUG

spring:
  application:
    name: "demo-transactions"
  threads:
    virtual:
      enabled: true
  mvc:
    async:
      request-timeout: 600000 # milliseconds applied to server sent events
  profiles:
    default: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # full qualified connection pool name
    hikari:
      connection-timeout: 5000 # milliseconds a client will wait for a free connection from pool
      maximum-pool-size: 3 # max pool size maintained by the cp
      minimum-idle: 1 # minimum number of idle connections the cp will maintain
      idle-timeout: 30000 # milliseconds a connection is allowed to sit idle in cp
      max-lifetime: 120000 # max duration of a connection before it's been closed by cp
      auto-commit: true #default
    url: ${CQRS_DEMO_CONNECTION_STRING}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      generate_statistics: true

    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        default_schema: transactions
  flyway:
    enabled: true
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    url: ${FLYWAY_URL}
    schemas:
      - transactions
      - query
    locations:
      - classpath:db
