spring:
  datasource:
    url: jdbc:sqlserver://localhost:1434;database=cqrs-meets-hexagonal;encrypt=false;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sa
    password: Aut0mat0rs!
  flyway:
    user: SA
    password: Aut0mat0rs!
    url: jdbc:sqlserver://localhost:1434;database=cqrs-meets-hexagonal;encrypt=false;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
