openapi: 3.0.3
info:
  title: CQRS meets hexagonaö - OpenAPI 3.0
  description: |-
  termsOfService: https://swagger.io/terms/
  contact:
    email: etlb@aviatar.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
tags:
  - name: create-account
    description: Image search

paths:
  /api/v1/create-account:
    post:
      tags:
        - create-account
      summary: >
        Search for Images
      description: >
        Search for Images
      operationId: createAccount
      requestBody:
        description: Event to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: returns list of items and an empty arry in case the query has no results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
        accountNumber:
          type: string
        customerNumber:
          type: string

    Customer:
      type: object
      properties:
        id:
          type: string
        customerNumber:
          type: string





